### ISSUE TITLE
Todo #2: QOL changes

### ISSUE THREAD

**Issue by markmcrg** [optighost/table-scraper-extension#2]
- [ ] Add an icon
- [ ] Add badges to indicate how many tables/rows scraped
- [x] Edit README file for clarity
